FROM node:latest

RUN mkdir -p /usr/src/app



# RUN npm install -g npm@7.5.4

ADD src /usr/src/app/src
ADD public /usr/src/app/public

WORKDIR /usr/src/app
COPY package.json /usr/src/app/

RUN npm install create-react-app

# RUN npm start

# CMD ['npm', 'start']